apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argocd-invalid-url
  namespace: argocd
spec:
  destination:
    namespace: hello-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    #
    # A  valid repository  needs to  be connected  to ArgoCD  und this
    # needs to  be set accordingly. If  it is public id  does not even
    # need to be "connected" first .. It will work with this Repo too
    #
    #     https://github.com/alexei-matveev/hello-argocd.git
    #
    # but you may want to use your local copy ...
    #
    repoURL: https://fixme.localhost/git/hello-argocd.git
    path: hello-argocd
    targetRevision: HEAD
