#
# Just a comment.   Hm, the problem with Unicode text  like "xxx" does
# not seem to affect v2.0.4 when  the Application is confugured to use
# "Directory"  as a  manifest provider.   The bug  was reported  for a
# Kustomization project and ArgoCD v2.0.0 [1].
#
# The moment you  add add kustomization.yaml listing this  secret as a
# resource you will get the error message:
#
#     yaml: invalid trailing UTF-8 octet
#
# [1] https://github.com/argoproj/argo-cd/issues/6706
#
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fixme
stringData:
  unused: "hello, argocd!"
